GitSquared/edex-ui

src/package.json
Filled the mail field to allow `electron-builder` to build a pacman package.
=> Fixed electron-builder crash because of missing field

.gitignore
I use WebStorm for development and it creates this folder for project settings and stuff. You can be more granular with how you choose to ignore files from this folder (see [this StackOverflow post](https://stackoverflow.com/questions/11968531/what-to-gitignore-from-the-idea-folder)) but I think it's probably overkill -- I don't really want to clutter up the repository unless other people start developing on this using JetBrains IDEs.
=> Ignore JetBrains project folder

src/_renderer.js
* archlinux:
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
ID_LIKE=archlinux
ANSI_COLOR="0;36"
HOME_URL="https://www.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"
* manjaro:
NAME="Manjaro Linux"
ID=manjaro
ID_LIKE=arch
PRETTY_NAME="Manjaro Linux"
ANSI_COLOR="1;32"
HOME_URL="https://www.manjaro.org/"
SUPPORT_URL="https://www.manjaro.org/"
BUG_REPORT_URL="https://bugs.manjaro.org/"
Change archlinux to arch make other archlinux-like users see the greeting too
=> Let arch-like(manjaro) users enjoy greeting too

src/classes/keyboard.class.js
This fixes an off-by-one comparison against the length of the array being iterated over. I found this loop condition error on the [list of alerts for this project](https://lgtm.com/projects/g/GitSquared/edex-ui/alerts) on LGTM. (there are a couple of other alerts that would probably be good to look at too!)
*(Full disclosure: I'm part of the team behind LGTM.com)*
=> fix index out of bounds issue

.gitignore, .gitmodules, file-icons-generator.js, package.json
It makes sense to maintain the `file-icons` as `git submodules` since it becomes easier to maintain and manage as it can be automatically done with `git`.
The current method of adding and updating `file-icons` ( with basic `git clone` and `git pull` commands ) looks kind of clumsy and hack-y.
=> :recycle: convert file-icons to git submodules

src/_renderer.js
Because who wouldn't like to see "Welcome back, John Wick"? :)
On a more serious note, I wasn't sure whether or not to add it to the initial settings file or not, because an empty string (or null) would represent an auto-detected username, but this might not make immediate sense to someone looking at the settings file (since comments aren't allowed in json).
Alternatively, I guess it could also maybe write the username in the initial settings file.
=> Add option to configure the displayed welcome username

src/_renderer.js, src/classes/filesystem.class.js
For example, and image titled "abc #abc abc.jpg" will not load, as the browser will interpret # as an anchor point instead.
=> Fix media with hashtags in their filenames

src/classes/filesystem.class.js
Switching between tabs with the same path will refresh the filesystem widget, even if it's not required.
I'm wondering if down the road, a better solution would be to separate the model/view, so that a cache of the filesystem can be stored for each open tab (or a maximum of n tabs), and then a single filesystem widget can then just switch between the current model that it's displaying.
=> Don't refresh filesystem if path hasn't changed

src/assets/css/main_shell.css
added a 10 px padding at the bottom of the terminal in order to avoid invisible text.
=> added padding at the terminal bottom

package.json
Close #816
Fixed the issue with the start script
=> fixed start script for windows

src/classes/filesystem.class.js
I found an issue while poking about the master branch on Windows where if you click an image in the filesystem, the image wouldn't load. It came up with an error in the dev console that looked something like this:
```
/C:/%5CUsers%5CSurge%5CDesktop%5Cwofrpg-site-NEW%5Cmain%5Cimages%5Cicon.png:1 GET file:///C:/%5CUsers%5CSurge%5CDesktop%5Cwofrpg-site-NEW%5Cmain%5Cimages%5Cicon.png net::ERR_FAILED
Image (async)
Modal @ modal.class.js:90
FilesystemDisplay.openMedia @ filesystem.class.js:570
onclick @ ui.html:1
```
I fixed the issue by adding a line in the `openMedia` function of the filesystem class that replaces all backslashes with forward slashes. It could definitely be done a lot better, but this does work without any issues.
=> Fix issue where images wouldn't load from general filesystem on Windows

src/classes/filesystem.class.js
#758 - Don't refresh file view if only file contents have changed.
On my machine, I observed the view constantly refreshing when in my home directory.  This was due to a file being frequently updated (.xsession-errors).  Each time this file was updated, the fw.watch callback was triggered and the view was refreshed.
=> Fixed issue #758

src/_renderer.js, src/assets/css/modal.css, src/classes/filesystem.class.js
Not sure if this would be useful or not, but I added a text editor that you can use through the file system. You can click a file in the file explorer and it will open a popup that displays the filename (and extension), and the content of the file that's currently there. I've provided screenshots as well.
Open in the tron-disrupted theme
Open in the red theme
Right now, the only kinds of files that can be opened are HTML, CSS, Javascript, XML, Yaml, Java, C#, C++ and H, Markdown, Batch and Shell, GDscript ([godot engine](https://godotengine.org/)), JSON (excludes the themes, keyboards, settings.json, and shortcuts.json), plain text, and log files, though that list can be expanded as needed.
In the future, I might try to make the different file types able to be differentiated by their …
=> Implement a text editor feature

src/classes/terminal.class.js
The issue described a crash when opening a previously closed tty instance. The issue appeared to be windows specific, as when I tested this on my raspberry pi the issue did not occur. All I did was add a try catch block where the terminal gets resized and ignore the error, which appeared to fix the issue.
=> Fix issue #873

src/_multithread.js
possibly causes an issue with leaving a core free? seeing the changes in the latest commit on master
=> fix logic error in last commit

package.json
Appimage construction used to compress files aggressively. Using roughly no compression reduces the start time by ~90%.
Closes #893
=> Set Appimage compression rate to `normal`

src/classes/sysinfo.class.js
Removes code `|| bat.timeremaining === -1` due to causing issues with the battery, fixes #833
=> Fix issue #833

src/assets/css/mod_processlist.css, src/classes/toplist.class.js
Wish I had thought of this before you merged the other PR. But I added the ability to control how the process list modal sorts processes. It defaults to the same method as the toplist, but clicking on a column in the table header will now make it sort the processes by the value in that column.
=> Improvements on process list modal

README.md, package.json, src/package.json
Hey I recently ran into some issues starting the project on mac: 
```
npm run start                               
> edex-ui@3.0.0-pre start
> node_modules\.bin\electron src --nointro
sh: node_modules.binelectron: command not found
npm ERR! code 127
```
I was able to find a work around when I updated the file pathing in the `package.json` to not include back slashes. I tested the start command on a windows machine and the current master version worked fine, so I broke out the commands to be seperate depending on the file path conventions and updated the README to include them both. 
I notice that the build steps take a similar approach as the one I've provided, let me know if there is anything else we need to get this merged. !
=> Starting on non windows fix

package.json, src/classes/filesystem.class.js, src/package-lock.json, src/package.json
Small update to the file editor I pushed a while ago, adding python and a few other extensions to the list of file types that are able to be opened by eDEX
=> feat: more file types available in file editor (#975) #973

src/_renderer.js
Modification to restrict Fix#265 to Win32 and prevent inadvertent Alt-F4 shutdown on *nix OS.
=> fix: restrict fix #265 to Win32, close #1063

src/_renderer.js
Fixes an issue where the `forceFullscreen` setting would be removed whenever the settings file was modified by the GUI settings editor.
=> fix: 'forceFullscreen' being overwritten by settings GUI

src/_renderer.js
=> fix: change openItem to openPath - close #1158

src/classes/keyboard.class.js
Replace tabs by spaces in keyboard.class.js to be consistent with the rest of the codebase.
=> style: replace tabs by spaces
