GitSquared/edex-ui

.travis.yml
package.json

chore(package): update electron-builder to version 19.42.1

---

src/_renderer.js
src/classes/ramwatcher.class.js

Clean code for release

---

src/assets/kb_layouts/de-DE.json

Not quite sure about alt_cmd lines, but layout is working well for me

 Added german de-DE keyboard layout

---

src/classes/locationGlobe.class.js

- Created `addRandomConnectedPoints` function pretty self explanatory.
- Created functions for pin and markers removal (clode cleanup)
- Replaced big "try catch"s with a async functions using `.then` and `.catch` (code cleanup)

Added random connector points like in the movie, cleaned globe code.

---

file-icons-generator.js
src/_renderer.js
src/classes/keyboard.class.js

https://lgtm.com/projects/g/GitSquared/edex-ui/rev/c98b139da9c5479681af0e545f032cc601f1fc01

:rotating_light: Lint fixes

---

src/_boot.js
src/_renderer.js
src/classes/audiofx.class.js

This option can be useful for people who would like to keep the sound style of eDEX-UI, but who are annoyed by constant clicking.

Added an option to disable annoying SFX

---

src/_renderer.js
src/package-lock.json
src/package.json

While using eDEX-UI on Windows, I noticed that my name did not appear at startup. I searched for solutions and the best suitable in my mind is the [username](https://www.npmjs.com/package/username) library, because it is lightweight and very simple to use. 
It has a lot of fallback methods to get a username and runs just fine on Linux, Windows and macOS. It would be super cool if you could take this method into consideration!
Kind Regards,
Niklas

Use username library for name detection

---

README.md

Fix typo in gitmoji link

---

README.md

This project was featured in the "Web Page" Telegram Channel: https://t.me/tproger_web/329
Google-translated post text with some fixes:
> Want to imagine yourself being a hacker in a Hollywood movie? Or just need to make it look like you're doing a very important job?
> 
> Then this futuristic terminal is for you.
> 
> Installation instructions and development details: https://github.com/GitSquared/edex-ui

Add featured on Telegram Channel "Web Page"

---

src/assets/kb_layouts/tr-TR-F.json
src/assets/kb_layouts/tr-TR-Q.json

This commit adds Turkish Q and F keyboards layouts.

Add Turkish keyboard layouts (Q and F)

---

src/assets/kb_layouts/en-NORMAN.json

This commit adds [Norman keyboards layout](https://normanlayout.info/)

Add Norman keyboard layout

---

src/assets/kb_layouts/it-IT.json

Add standard Italian keyboard layout

---

src/classes/conninfo.class.js

I find graph only network traffic hard to read. Could be usefull to also display a numeric value.

Network Traffic Upload and Downlaod value

---

src/classes/filesystem.class.js

Issue where loading theme through file explorer fixed. #861

Fix issue #861

---

src/assets/themes/chalkboard-notype.json

Just adding the keyboardless version of the chalkboard theme.

Added chalkboard-notype theme

---

src/assets/css/mod_processlist.css
src/assets/css/mod_toplist.css
src/classes/filesystem.class.js
src/classes/toplist.class.js
src/ui.html

Don't know how useful this will be, but I added a new modal which gives a more detailed listing of active processes. It is opened by clicking the top processes list.

feat: added a more detailed process view modal

---

src/classes/toplist.class.js

Mentioned in #929 
Fixing minor error where uncaught TypeErrors would show in the developer console in regards to the toplist class trying to update the contents of the modal when the modal is not present.

Fix TypeError with toplist modal

---

src/assets/themes/navy-notype.json
src/assets/themes/navy.json

I figured this type of blue color makes the whole terminal so cool.

feat: added new 'Navy' theme

---

src/assets/themes/navy-disrupted.json

I hope I'm not too late for this one. :)

feat: added Navy-disrupted style theme

---

src/classes/sysinfo.class.js

Enhances display of uptime by adding day indicator and contrasting opacity between labels and variables

feat: enhance display of uptime by adding day indicator #1065

---

src/assets/themes/cyborg-focus.json
src/assets/themes/cyborg.json

Featuring tall centered term window on cyborg-focus theme.
EDIT: updated screenshot

feat: Add cyborg and cyborg-focus themes

---

src/assets/kb_layouts/nl-BE.json

Small contribution to this very cool project for people using a Belgian Keyboard.

nl-be keyboard file added

---

src/assets/kb_layouts/sv-SE.json

Used the da-DK profile and just changed the åäö keys to the swedish ones.

feat: add swedish keyboard
